### ISSUE TITLE
README.md Missing

### ISSUE THREAD

**Issue by ShreyJaiswal1** [Toosmo/zerotwo#260]
Please add README.md file and give instructions for how to use this repository

**Comment by Toosmo** [comment]
This repository only acts as a way for me to automate dependency updates and building Docker images, so no support will be provided.

However, the project can be easily run with [Python](https://www.python.org/) (3.8 or greater) and [Poetry](https://python-poetry.org/) after you've created a `config.json` file in the `config` directory. An example can be found in the [`example-config.json`](https://github.com/Toosmo/zerotwo/blob/master/config/example-config.json) file.

If you wish to use the music features, you must run a [Lavalink](https://github.com/freyacodes/Lavalink/) instance of your own.
